---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cleanup-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-cel-expression: |
      headers['x-github-event'] == "pull_request" && body.action == "closed"  
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: repo_name
      value: "{{ repo_name }}"
    - name: source_branch
      value: "{{ source_branch }}"
    - name: namespace
      value: demo-application
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: repo_name
      - name: source_branch
      - name: namespace
    workspaces:
      - name: basic-auth
    tasks:
      - name: uninstall-helm-chart
        taskRef:
          name: helm-uninstall
          kind: ClusterTask
        params:
          - name: release_namespace
            value: $(params.namespace)
          - name: release_name
            value: $(params.repo_name)-$(params.source_branch)
  workspaces:
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
